#Example of New Players Table(GoodLoose vs. GoodTight)
GoodLoose_vs_GoodTight = read.csv("GoodLoose_vs_GoodTight.csv")

# Calculate incremental average
incremental_avg = function(data){
  n = length(data)
  result = NULL
  m = 0
  for(i in 1:n){
    result[i] = ((i-1)*m +data[i])/(i)
    m = result[i]
  }
  return(result)
}

#Example of New Players Table(GoodLoose vs. GoodTight)
# (GoodLoose|GoodTight) GoodLoose is big blind, GoodTight is small blind
a1 = incremental_avg(GoodLoose_vs_GoodTight$p1_luck[1:1500])
a1_lb = a1 - 1.96*sd(a1) / sqrt(1500)
a1_ub = a1 + 1.96*sd(a1) / sqrt(1500)
a2 = incremental_avg(GoodLoose_vs_GoodTight$p2_luck[1:1500])
a2_lb = a2 - 1.96*sd(a2) / sqrt(1500)
a2_ub = a2 + 1.96*sd(a2) / sqrt(1500)
a3 = incremental_avg(GoodLoose_vs_GoodTight$p1_skill[1:1500])
a3_lb = a3 - 1.96*sd(a3) / sqrt(1500)
a3_ub = a3 + 1.96*sd(a3) / sqrt(1500)
a4 = incremental_avg(GoodLoose_vs_GoodTight$p2_skill[1:1500])
a4_lb = a4 - 1.96*sd(a4) / sqrt(1500)
a4_ub = a4 + 1.96*sd(a4) / sqrt(1500)
a5 = incremental_avg(GoodLoose_vs_GoodTight$p1_chip[1:1500])
a5_lb = a5 - 1.96*sd(a5) / sqrt(1500)
a5_ub = a5 + 1.96*sd(a5) / sqrt(1500)
a6 = incremental_avg(GoodLoose_vs_GoodTight$p2_chip[1:1500])
a6_lb = a6 - 1.96*sd(a6) / sqrt(1500)
a6_ub = a6 + 1.96*sd(a6) / sqrt(1500)

plot(a1,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Loose Player(BB) Luck Profit ")
lines(a1_lb, lty = "dashed", col = "green")
lines(a1_ub, lty = "dashed", col = "green")
plot(a2,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Tight Player(SB) Luck Profit ")
lines(a2_lb, lty = "dashed", col = "green")
lines(a2_ub, lty = "dashed", col = "green")
plot(a3,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Loose Player(BB) Skill Profit ")
lines(a3_lb, lty = "dashed", col = "green")
lines(a3_ub, lty = "dashed", col = "green")
plot(a4,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Tight Player(SB) Skill Profit ")
lines(a4_lb, lty = "dashed", col = "green")
lines(a4_ub, lty = "dashed", col = "green")
plot(a5,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Loose Player(BB) Chips Change ")
lines(a5_lb, lty = "dashed", col = "green")
lines(a5_ub, lty = "dashed", col = "green")
plot(a6,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Tight Player(SB) Chips Change ")
lines(a6_lb, lty = "dashed", col = "green")
lines(a6_ub, lty = "dashed", col = "green")

# (GoodTight|GoodLoose) GoodTight is big blind, GoodLoose is small blind
b1 = incremental_avg(GoodLoose_vs_GoodTight$p2_luck[1501:3000])
b1_lb = b1 - 1.96*sd(b1) / sqrt(1500)
b1_ub = b1 + 1.96*sd(b1) / sqrt(1500)
b2 = incremental_avg(GoodLoose_vs_GoodTight$p1_luck[1501:3000])
b2_lb = b2 - 1.96*sd(b2) / sqrt(1500)
b2_ub = b2 + 1.96*sd(b2) / sqrt(1500)
b3 = incremental_avg(GoodLoose_vs_GoodTight$p2_skill[1501:3000])
b3_lb = b3 - 1.96*sd(b3) / sqrt(1500)
b3_ub = b3 + 1.96*sd(b3) / sqrt(1500)
b4 = incremental_avg(GoodLoose_vs_GoodTight$p1_skill[1501:3000])
b4_lb = b4 - 1.96*sd(b4) / sqrt(1500)
b4_ub = b4 + 1.96*sd(b4) / sqrt(1500)
b5 = incremental_avg(GoodLoose_vs_GoodTight$p2_chip[1501:3000])
b5_lb = b5 - 1.96*sd(b5) / sqrt(1500)
b5_ub = b5 + 1.96*sd(b5) / sqrt(1500)
b6 = incremental_avg(GoodLoose_vs_GoodTight$p1_chip[1501:3000])
b6_lb = b6 - 1.96*sd(b6) / sqrt(1500)
b6_ub = b6 + 1.96*sd(b6) / sqrt(1500)

plot(b1,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Tight Player(BB) Luck Profit")
lines(b1_lb, lty = "dashed", col = "green")
lines(b1_ub, lty = "dashed", col = "green")
plot(b2,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Loose Player(SB) Luck Profit")
lines(b2_lb, lty = "dashed", col = "green")
lines(b2_ub, lty = "dashed", col = "green")
plot(b3,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Tight Player(BB) Skill Profit")
lines(b3_lb, lty = "dashed", col = "green")
lines(b3_ub, lty = "dashed", col = "green")
plot(b4,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Loose Player(SB) Skill Profit")
lines(b4_lb, lty = "dashed", col = "green")
lines(b4_ub, lty = "dashed", col = "green")
plot(b5,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Tight Player(BB) Chips Change")
lines(b5_lb, lty = "dashed", col = "green")
lines(b5_ub, lty = "dashed", col = "green")
plot(b6,xlab="Number of hands", ylab="Mean profit per hand($)", main = "Good Loose Player(SB) Chips Change")
lines(b6_lb, lty = "dashed", col = "green")
lines(b6_ub, lty = "dashed", col = "green")
